#file handling - To read and write a file
myfile = open("rockxxy.txt", "w")
myfile.write("This is added to our file.")
myfile = open("rockxxy.txt", "r")
print(myfile.read())
myfile = open("rockxxy.txt","w")
myfile.write("Now, please add this and close the file.")
myfile = open("rockxxy.txt", "r")
print(myfile.read())
myfile = open("rockxxy.txt", "w")
myfile.write("This is being added too.")
myfile = open("rockxxy.txt","r")
print(myfile.read())
myfile = open("rockxxy.txt","w")
myfile.write("This will not get displayed unless/until 'r' is being used.")
myfile = open("rockxxy.txt","r")
print(myfile.read())
myfile.close()

